√ config for CI

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -8,21 +8,27 @@ jobs:
       - image: cimg/python:3.8
       - image: postgres:13.3
         environment:
-          POSTGRES_USER: youruser
-          POSTGRES_DB: yourtestdb
-          POSTGRES_PASSWORD: yourpassword
+          POSTGRES_USER: nathan
+          POSTGRES_PASSWORD: pleased
+          POSTGRES_DB: capstone_test  # Adjust based on specific test, dev, or prod environment
+
     steps:
       - checkout
+      - run:
+          name: Install dependencies
+          command: |
+            sudo apt-get update
+            sudo apt-get install -y postgresql-client
       - run:
           name: Wait for DB
           command: |
             for i in `seq 1 10`;
             do
-              nc -z localhost 5432 && echo Success && exit 0
-              echo -n .
+              PGPASSWORD=pleased psql -h localhost -U nathan -d capstone_test -c "SELECT 1" && echo "Success" && exit 0
+              echo -n "."
               sleep 1
             done
-            echo Failed waiting for DB && exit 1
+            echo "Failed waiting for DB" && exit 1
       - python/install-packages:
           pkg-manager: pip
           pip-dependency-file: requirements.txt
